import { escapeHTML, formatTimestamp } from '../utils/format.js';

export function exportJson(result) {
  const blob = new Blob([JSON.stringify(result, null, 2)], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const safeName = (result.details?.registeredDomain || 'scan').replace(/[^a-z0-9.-]/gi, '_');

  const a = document.createElement('a');
  a.href = url;
  a.download = `url-guardian-${safeName}-${Date.now()}.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

const SEVERITY_PRINT_COLOR = { low: '#6fae3a', medium: '#b9821f', high: '#c44a1e', critical: '#b3132f' };

/**
 * "Export PDF" here means: build a clean, light-background report view and
 * hand off to the browser's native print dialog (where "Save as PDF" is a
 * built-in destination on every major browser/OS). A from-scratch PDF
 * encoder would mean pulling in a third-party library like jsPDF — which
 * conflicts with the "no frameworks/dependencies" brief — so this reuses
 * what the platform already gives you for free.
 */
export function exportPdf(els, result) {
  const d = result.details;
  const levelKey = (result.level || '').toLowerCase();

  const findingsHtml =
    result.findings.length === 0
      ? '<p style="font-size:12.5px;color:#333;">No phishing indicators triggered by this rule set.</p>'
      : result.findings
          .map(
            (f) => `
        <div class="print-finding">
          <span class="pf-title">${escapeHTML(f.title)}<span class="pf-sev" style="background:${
              SEVERITY_PRINT_COLOR[f.severity] || '#666'
            }">${escapeHTML(f.severity)}</span></span>
          <div class="pf-desc">${escapeHTML(f.description)}</div>
          <div class="pf-rec"><strong>Recommendation:</strong> ${escapeHTML(f.recommendation)}</div>
        </div>`
          )
          .join('');

  els.printReport.innerHTML = `
    <div class="print-report-header">
      <h1>URL Guardian — Scan Report</h1>
      <span>${formatTimestamp(result.timestamp)}</span>
    </div>
    <div class="print-section">
      <h2>Scanned URL</h2>
      <div class="print-url">${escapeHTML(result.url)}</div>
    </div>
    <div class="print-section print-score-row">
      <strong style="color:${SEVERITY_PRINT_COLOR[levelKey] || '#111'}">${result.score}/100</strong>
      <span>${escapeHTML(result.levelLabel || result.level)}</span>
    </div>
    <div class="print-section">
      <h2>Recommendation</h2>
      <p style="font-size:12.5px;color:#333;">${escapeHTML(result.recommendation)}</p>
    </div>
    <div class="print-section">
      <h2>URL Details</h2>
      <table class="print-details-table">
        <tr><td>Protocol</td><td>${escapeHTML((d.protocol || '').replace(':', ''))}</td></tr>
        <tr><td>Hostname</td><td>${escapeHTML(d.hostname)}</td></tr>
        <tr><td>Registered Domain</td><td>${escapeHTML(d.registeredDomain)}</td></tr>
        <tr><td>Subdomain</td><td>${escapeHTML(d.subdomain || '—')}</td></tr>
        <tr><td>TLD</td><td>${escapeHTML(d.tld || '—')}</td></tr>
        <tr><td>Port</td><td>${escapeHTML(d.explicitPort || d.port || '—')}</td></tr>
        <tr><td>URL Length</td><td>${d.urlLength} characters</td></tr>
      </table>
    </div>
    <div class="print-section">
      <h2>Findings (${result.findings.length})</h2>
      ${findingsHtml}
    </div>
    <div class="print-footer">
      Generated by URL Guardian, a client-side rule-based heuristic scanner. This report reflects pattern-matching analysis only and is not a guarantee of safety or malicious intent.
    </div>`;

  window.print();
}
